<?php

namespace App;

use App\Mail\ProjectCreated;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = [
        'title', 'description', 'owner_id'
    ];
    public function tasks(){
        return $this->hasMany(Task::class);
    }
    public function addTask($task){

        $this->tasks()->create($task);
//        return Task::create([
//            'project_id' => $this->id,
//            'description' => $description
//        ]);
    }
    public function owner(){
        return $this->belongsTo(User::class);
    }
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function ($project){
            Mail::to($project->owner->email)->send(
                new ProjectCreated($project)
            );
        });
    }
}
